### ISSUE TITLE
predict_small_images still fails on undersized images

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-redis-consumer#150]
It looks like #148 didn't fully solve the issue. I tried submitting an image of size (2, 311, 145) and got the error message below. This looks to be further down in the processing scheme, we may need to add a higher level test for small images. 

```
Job Failed: Traceback (most recent call last):
File "/usr/src/app/redis_consumer/consumers/base_consumer.py", line 202, in consume
status = self._consume(redis_hash)
File "/usr/src/app/redis_consumer/consumers/multiplex_consumer.py", line 124, in _consume
image = self.predict(image, model_name, model_version)
File "/usr/src/app/redis_consumer/consumers/base_consumer.py", line 608, in predict
model_dtype)
File "/usr/src/app/redis_consumer/consumers/base_consumer.py", line 531, in _predict_small_image
in_tensor_dtype=model_dtype)
File "/usr/src/app/redis_consumer/consumers/base_consumer.py", line 311, in grpc_image
prediction = client.predict(req_data, settings.GRPC_TIMEOUT)
File "/usr/src/app/redis_consumer/grpc_clients.py", line 185, in predict
response = self._retry_grpc(request, request_timeout)
File "/usr/src/app/redis_consumer/grpc_clients.py", line 155, in _retry_grpc
raise err
File "/usr/src/app/redis_consumer/grpc_clients.py", line 123, in _retry_grpc
response = api_call(request, timeout=request_timeout)
File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
return _end_unary_response_blocking(state, call, False, None)
File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.INVALID_ARGUMENT
details = "2 root error(s) found.
(0) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,256,311,2] vs. shape[1] = [1,256,256,2]
[[{{node panopticnet/concatenate_location/concat}}]]
[[StatefulPartitionedCall/_791]]
(1) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,256,311,2] vs. shape[1] = [1,256,256,2]
[[{{node panopticnet/concatenate_location/concat}}]]
0 successful operations.
0 derived errors ignored."
debug_error_string = "{"created":"@1608015080.944543825","description":"Error received from peer ipv4:10.43.253.0:8500","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"2 root error(s) found.\n (0) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,256,311,2] vs. shape[1] = [1,256,256,2]\n\t [[{{node panopticnet/concatenate_location/concat}}]]\n\t [[StatefulPartitionedCall/_791]]\n (1) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,256,311,2] vs. shape[1] = [1,256,256,2]\n\t [[{{node panopticnet/concatenate_location/concat}}]]\n0 successful operations.\n0 derived errors ignored.","grpc_status":3}"
```

**Comment by willgraf** [comment]
`_predict_small_image` only pads the small side, but does not crop the large side.

I think the `deepcell.applications` project fixes this very cleanly.
